const FILE_COUNT_EXPECTATIONS = {
  NON_FORM_APP: 9,
  FORM_1_PAGE: 21,
  FORM_1_PAGE_WITH_VETS_JSON_SCHEMA: 20,
  FORM_4_PAGES: 24,
  FORM_4_PAGES_WITH_VETS_JSON_SCHEMA: 23,
  FORM_ENGINE: 6,
};

module.exports = {
  FILE_COUNT_EXPECTATIONS,
};
